version: '3'
services:
    webapp:
        image: ${DOCKER_IMAGE}
        container_name: ${PROJECT}
        restart: always
        ports:
            - ${PORT}:80
        network_mode: "host"
        environment:
            profile: ${PROFILE}
        volumes:
          - ${APP_DIR}/storage:/usr/share/nginx/html/src/storage
