version: '3'
services:
    webapp:
        image: ${DOCKER_IMAGE}
        container_name: ${PROJECT}
        restart: always
        ports:
            - ${PORT}:${PORT}
        environment:
            profile: ${PROFILE}
        
